openapi: 3.0.2

info:
  title: Structured OpenAPI Schema
  description: description
  version: '1.0'

servers:
  - url: http://localhost:0000/{api_version}
    description: Local API Server
    variables:
      api_version:
        default: 'v1'
        enum:
          - 'v1'

tags:
  - name: user
    description: tag for user

paths:
  /users:
    $ref: ./paths/users.yml
  /users/{user_id}:
    $ref: ./paths/users-by-id.yml
