openapi: 3.0.2

info:
  title: Example Project
  version: '1.0'

servers:
  - url: http://localhost:PORT/{api_version}
    description: Local API Server
    variables:
      api_version:
        default: 'v1'
        enum:
          - 'v1'

paths:
  /users:
    get:
      responses:
        200:
          description: ok
