name: Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: cache node_modules
      id: node_modules_cache_id
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/node_modules
          distributions/*/node_modules
        key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
    - run: yarn install
    - run: yarn lint
    - run: yarn build
